# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "Preflight CLI for launch readiness checks"
  homepage "https://github.com/preflightsh/preflight"
  version "0.15.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.1/preflight_0.15.1_darwin_amd64.tar.gz"
      sha256 "971aedd108588044650a93870798be25f3585cbc4ca72d9a62791d21697112d3"

      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.1/preflight_0.15.1_darwin_arm64.tar.gz"
      sha256 "f44c574d65fe64af413f5399595554c60b12f61a9d82bcc68c4d6f8a04eb3d1e"

      define_method(:install) do
        bin.install "preflight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.1/preflight_0.15.1_linux_amd64.tar.gz"
      sha256 "5d5f5f5451ef0f26e1c69e2b998a1ed8f1edea949a01c91f7fbdd09b986d7044"
      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.1/preflight_0.15.1_linux_arm64.tar.gz"
      sha256 "03e4478f5f705267fca1ab2e716fa35d0096f710802396a24e7acd5ed3d1022e"
      define_method(:install) do
        bin.install "preflight"
      end
    end
  end
end
