# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "Preflight CLI for launch readiness checks"
  homepage "https://github.com/preflightsh/preflight"
  version "0.15.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.5/preflight_0.15.5_darwin_amd64.tar.gz"
      sha256 "63e4b5fc7c95b276331160637e73d5759d0034a516deb603c7f62d98d0378058"

      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.5/preflight_0.15.5_darwin_arm64.tar.gz"
      sha256 "fc97de2c983bf4e66641ae130b66625f8bcad37c6ba5b28929b6f8d261e29c1e"

      define_method(:install) do
        bin.install "preflight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.5/preflight_0.15.5_linux_amd64.tar.gz"
      sha256 "60c911344611834cb9f04258ded95a7d01df65191c6bcc4537a060b594455df7"
      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preflightsh/preflight/releases/download/v0.15.5/preflight_0.15.5_linux_arm64.tar.gz"
      sha256 "1c2e5571c2b13e8b3cb97fae1af3a9670dd1f1a040a586b472b4f8f6df12da5d"
      define_method(:install) do
        bin.install "preflight"
      end
    end
  end
end
